threads: 2  # simulate users
time_on: 600 # time to run attack
time_off: 600 # time to turn off attack
wait_between_requests: 0.01 # in secs
request:
  server_url: "http://knp.services/load" # - use carefully
  #server_url: "http://localhost:8081/load"  #"http://knp.services/load" # - use carefully
  method: post
  headers:
    Content-Type: "application/json"
  data:
    cpu_params: {"load": 0.9, "duration_seconds": 0.001}
logging:
  level: "DEBUG"
  log_name: "ddoser.attack"
